axondeepseg/axondeepseg

docs/source/documentation.rst

Two new notebooks were added last 2 weeks so I just added the info on the doc:
* `guide_dataset_building.ipynb` for the dataset generation.
* `training_guideline.ipynb` for the training.

Added info for dataset building and training notebooks in doc

---

AxonDeepSeg/data_management/data_augmentation.py

Encountered while writing tests for #76 and issue #112.
Really minor, the patch was just forgotten to be returned for the case of a rescaling factor too small (returned patch = input patch).

[BUG] Fixed if-case in rescaling func where patch value was not returned

---

AxonDeepSeg/ads_utils.py

Updated the Sentry opt-out message from:
`Note: you can opt out of Sentry reporting by changing the value of bugTracking to 0 in the file AxonDeepSeg/.adsconfig`
to display the full path of the location of the file to change to opt-out, e.g.:
`Note: you can opt out of Sentry reporting by changing the value of bugTracking to 0 in the file /Users/mathieuboudreau/neuropoly/github/axondeepseg/AxonDeepSeg/.adsconfig`
since for people who install via `pip`, the folder "AxonDeepSeg" created in their virtalenv folder may be difficult to find.

[SENTRY] Display full path to config file in Sentry opt-out message

---

AxonDeepSeg/__init__.py
AxonDeepSeg/data_management/data_augmentation.py
AxonDeepSeg/data_management/dataset_building.py

When running tests and/or calling certain functions, the following warnings appeared:
*/Users/mathieuboudreau/anaconda3/envs/ads36_venv/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.*
This happens in two locations, in our rescaling data augmentation tools, and in `raw_img_to_patches` function.
I resolved in this branch this by explicitly setting the mode value to `constant` in the function calls.
**However,**
by looking at the documentation, it appears to me that setting it to `reflect` might be the behaviour that we actually want? @perone what do you think?
...
mode : {‘constant’, ‘edge’, ‘symmetric’, ‘reflect’, ‘wrap’}, optional
Points outside the boundaries of the input are filled …

[REF] Resolve rescale mode warnings

---

requirements.txt

As pointed out by @perone, tensorflow might behave differently for newer versions, so we might as well stick with 1.3.0 as originally intended (although before, we had a req of >= 1.3.0, so whatever was installed at any given time was the most up to date version). I had fixed it to 1.9.0 as it was the most up-to-date version at the time (thus, the one being installed anyways). Also, the CUDA libraries installed on Rosenberg at the moment (or at least, for me as a user) aren't compatible with tensorflow versions >= 1.5.0.
Also removing the tifffile requirement. That one was added recently because imageio shouts warnings for tiffiles that it's not optimized for speed without tifffile installed (see: https://github.com/imageio/imageio/issues/350). This worked fine for me on my local …

[REF] Revert tensorflow req to 1.3.0 and remove tifffile requirement

---

notebooks/getting_started.ipynb
notebooks/morphometrics_extraction.ipynb
notebooks/segmentation_image.ipynb

Replaced print " " with print("") on a few Jupyter notebooks (which crashed with Py3K).

DOC: Fixed print syntax with Py3k

---

AxonDeepSeg/morphometrics/compute_morphometrics.py
test/morphometrics/test_compute_morphometrics.py

Will fix #190. 
Now, the thickness and area of the myelin is relative to its corresponding axon.
Error handling for equivalent diameter and area values has been added with the `_check_measures_are_relatively_valid` method.
`test_compute_morphometrics.py`: Add a unit test  for cases where no myelin was detected.

Change Evaluation Of Myelin Thickness And Area

---

docs/source/conf.py
docs/source/documentation.rst

* Adds some additional instructions in case `conda` is not available in new sessions after installation
* Fixes a bug that cause ReadTheDocs to fail (cannot use `pathlib`/`Path`calls to the RTD config file, as it's not compiled using our environment)

Update installation doc + fix RTD bug

---

AxonDeepSeg/apply_model.py
AxonDeepSeg/data_management/data_augmentation.py
AxonDeepSeg/data_management/dataset_building.py
AxonDeepSeg/data_management/input_data.py
AxonDeepSeg/network_construction.py
AxonDeepSeg/train_network.py
AxonDeepSeg/visualization/visualize.py

This PR handles the bug import error occurred while importing ADS scripts. Errors such as 
```
Traceback (most recent call last):
File "/Users/vasudevsharma/PycharmProjects/axondeepseg/AxonDeepSeg/apply_model.py", line 13, in <module>
from .visualization.get_masks import get_masks
ModuleNotFoundError: No module named '__main__.visualization'; '__main__' is not a package
```
are commonly faced when working on  ADS scripts.

Fix relative imports

---

docs/source/documentation.rst
setup.py

Changes
* Only allow ADS installation for Python versions 3.6.x 
* Revert Path() syntax in setup.y, which errors for versions before <=3.5 without a descriptive message (related to Python version).
If someone tried to install ADS with an incompatible Python version, they will now get something like following message.
>`AxonDeepSeg requires Python '>=3.6, <3.7' but the running Python is 3.5.2`
I looked into if I could customise this message or append one, but after a lot of searching it appears it's not possible (for unsuccessful installs).

Enforce Python 3.6.x version during setup

---

CHANGELOG.md
docs/source/documentation.rst
readthedocs.yml

Changes:
* Removes hardcoded changelog in RTD
* Converts the CHANGELOG.md to a RTD-compatible syntax
* Fixes the RTD build (which has been broken for a few days) by adding a readthedocs.yml file which enforces a Python 3.6 version during the RTD build.
Check out the final RTD build of this branch here:  https://axondeepseg.readthedocs.io/en/changelog/documentation.html#

 Remove hardcoded RTD changelog; import instead CHANGELOG.md

---

.travis.yml

Currently not needed to support headless graphics in ADS.

[TRAVIS] Quickfix: Remove the before_script

---

AxonDeepSeg/morphometrics/compute_morphometrics.py
ads_plugin.py
requirements.txt

This branch adds a button in the FSLeyes GUI to compute and save morphometrics from a segmented image.
**Workflow**
After you've loaded and segmented an image using the ADS prediction model, you click the new "Compute morphometrics" button here:
which will compute the morphometrics for each axon. After that's done (a few seconds), a popup window will appear for you to select where to save the Excel file containing these data, and to name it:
You can then double click the file after it's saved:
And view the table of morphometrics data for this image:

[GUI] Add buton to compute and save morphometrics

---

docs/source/documentation.rst

Compiled ReadTheDocs branch displaying the change: https://axondeepseg.readthedocs.io/en/fsleyes_restart_bug/documentation.html#graphical-user-interface-gui-optional

[Doc] Add notice about restarting FSLeyes to see the plugin for installation

---

AxonDeepSeg/models/download_model.py
test/models/test_download_models.py
test/test_config_tools.py

Resolves #316 and #286
* If model folders already exists, deletes them before moving downloaded ones there
* Adds optional destination input to download_models
* Removed unused __main__ and renamed download_models function.
* Wrote tests for download_models.py (both basic and redownloading behaviour)
* Cleaned up a file that had an unused `pass` call.

Fix redownloading models bug

---

notebooks/00-getting_started.ipynb

Fixes #324 
- Added `resampled_resolutions` parameter in `axon_segmentation` function in section 2.2 of `00-getting_started.ipynb`.
- Added description of the parameter for the user.

Add resampled_resolutions parameter in getting_started notebook

---

AxonDeepSeg/postprocessing.py
ads_plugin.py

fixes #321 
ADDED: 
- If there's an overlap between the axon an the myelin mask, the myelin will have priority.
- A popup message in FSLeyes is displayed if there’s an overlap between the Axon mask and the Myelin mask to let the user know Myelin will have priority.

Remove overlap when saving masks

---

docs/source/documentation.rst

Updated documentation to add a warning about the re-download of default model folders when re-installing ADS.

Add warning to doc for re-download of model folders when re-installing

---

AxonDeepSeg/postprocessing.py
ads_plugin.py

Changes:
- A default extension (.xlsx) is added to the morphometrics file if the user didn't specify any.
- The font size of the numbers overlay is determined based on the mean axon diameter (in pixels, not in micrometers)

FSLeyes plugin: default morphometrics file extension and font size 

---

AxonDeepSeg/ads_utils.py

This PR fixes #361 
For some reason, those two lines in `ads_utils.download_data()` wouldn't work on Windows during the installation:
```
zf = zipfile.ZipFile(str(tmp_path))
zf.extractall(".")
```
I changed them to
```
with zipfile.ZipFile(str(tmp_path)) as zf:
zf.extractall(".")
```

Fix for the Windows installation

---

AxonDeepSeg/segment.py

Fixes #369 
TEM image contrasts are no longer inverted when using CLI pointing on a folder with multiple files.

Resolve bug that makes TEM data not segment well with multiple files

---

docs/source/documentation.rst

Related to #368 
Removed the instructions for the installation of the stable release via PyPI in RTD.
The only installation methods are now the development version via git clone, or via a link to download a zip from github.

Remove PyPI install instructions from RTD

---

.travis.yml
docs/source/documentation.rst

Related to #390 and #382.
Added downgrade to `h5py=2.10.0` after fsleyes installation in documentation and travis tests to avoid errors in `training_network.py` and `test_training_network.py`.
Tested on Linux.
All tests passed locally except `test_floodfill_axons_returns_expected_arrays` from `test_postprocessing.py`, as mentioned in #390 (unrelated to h5py and passing on travis).

Bug fix due to h5py package version in fsleyes

---

docs/source/CHANGELOG.md
docs/source/conf.py
docs/source/documentation.rst
docs/source/index.rst
docs/source/license_contributors.rst
setup.py

Fixes #367 
Added symlink to CHANGELOG.md in `docs/source` and requirement `recommonmark` in `conf.py` and `setup.py` to be able to display markdown properly.
Previous documentation was all on the same page, here I had to split the documentation in 3 sections (3 pages) in `index.rst` to display the markdown symlink correctly:
- Before CHANGLOG on one page (Introduction to Citation)
- CHANGELOG
- After CHANGELOG (Licensing and Contributors)
Docs is rendered here: https://axondeepseg.readthedocs.io/en/mhb-367-fix-changelog/
@jcohenadad, is the split in 3 parts ok with you? I could also split each section in individual pages like it is done for [ivadomed](https://ivadomed.org/en/latest/index.html) or [SCT](https://spinalcordtoolbox.com/en/stable/index.html).

Fix new changelog display in RTD

---

Dockerfile
requirements.txt

The current installation for MyBinder/Docker depends on the requirements.txt/setup.py file, however I think that `repo2docker` doesn't use the editable mode during the pip installation of our package (i.e. `pip install -e .`) and I haven't been able to find an option to do so. This is required to download the model in the repository of our cloned software; otherwise the models will be missing per my mention in the discussion of #413 .
This PR resolves this issue by using a Dockerfile that overrides the requirements.txt/setup.py installation that repo2docker does, and in it I explicitely clone the master branch of the repository and run `pip install -e .`. The only downside is that it does not automatically rebuild on MyBinder unless there has been a modification in the Dockerfile after a …

Add a Dockerfile

---

ads_plugin.py

The default file name for saving the morphometrics file in FSLeyes plugin is `Untitiled.xlsx`. This PR aims to change the default file name to a more intuitive file name such as `axon_morphometrics.xlsx.`
So, now when the morphometrics file is saved using the FSLeyes plugin, the default name would be `axon_morphometrics.xlsx`.
Fixes #465

Change the default name for saving the morphometrics file

---

AxonDeepSeg/segment.py
docs/source/documentation.rst
test/test_segment.py

As pointed out by Julien in the issue https://github.com/neuropoly/axondeepseg/issues/460, the `-o` flag for segmenting the images sounds like output, in this PR I've dropped the single dash overlap `-o` flag which is confusing.
1. First, do `pip install -e .` in this branch.
2. Segment an image using changed flag name; `axondeepseg -i <image_name.png> -t <Modality type> --overlap <overlap_value>`
https://axondeepseg--474.org.readthedocs.build/en/474/documentation.html#syntax
Fixes #460

Change the name of `-o` flag to `-overlap` flag

---

README.md

This quick PR aims to update the references of the ADS readme. The article that cites ADS --> https://www.sciencedirect.com/science/article/pii/S1361841520303042

Add a reference to `Readme.md`

---

AxonDeepSeg/postprocessing.py

Currently, the way we search for the font file in [postprocessing.py](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/postprocessing.py) doesn't work on newer versions of matplotlib (at least on Windows). This PR proposes a better and more flexible way to search for the font file.
The `FindFont` from `matplotlib.font_manager` function should be more reliable because it returns a default font path even if the one specified is not foud. In our case, it happens that the specified font is the default one.
Resolves #488

Change the way the font is found in the postprocessing.py script

---

docs/source/documentation.rst

This PR add the link to the video tutorial in RTD and the note about the ADScontrol tab not appearing after first installing the plugin. Both were removed by mistake in #452.
Fixes #492

Add tutorial video link in RTD

---

AxonDeepSeg/patch_management_tools.py

This PR fixes a bug where a black bar appears in the segmentation at the right of the image when the image width and height are the same, see #509 for details.
1. On master branch, segment an image where width=height. For reference, the `Maxo03_img60` image from our SEM dataset is 2001x2001. There will be a black bar on the right in the segmentation.
2. Checkout this branch and redo the segmentation --> no black bar.
3. Segment another image where width != height --> no black bar.
I did not add a test for this fix. As discussed today, we would need to add an integrity test for the prediction first (#508).
Fixes #509

Fix black bar segmentation bug when width = height

---

docs/source/documentation.rst

This PR adds a description of the columns headings of the `axon_morphometrics` file produces by ADS.
`solidity`, `eccentricity` and `orientation` descriptions are taken directly from the descriptions of `skimage measure regionprops`.

Doc: Add description of morphometrics columns headings

---

test/morphometrics/test_compute_morphometrics.py

This quick PR aims to generate simulated image of axon myelin using [simulate_axons.py](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/visualization/simulate_axons.py) script rather than having the simulated image stored on the OSF under `__test_files__/__test_simulated_axons__/SimulatedAxons.png`
The simulated image and the actual `SimulatedAxons` are almost the same, that is, they both have the same **gratio**, same **plane_angle**, and same **axon_radius**. In this PR tests have been modified to generate simulated image. 
Before successfully merging this PR into `master` branch, the `__test_files__` directory also needs to be updated (without`SimulatedAxons.png`)  on OSF. Here is the updated  zip [__test_files__.zip](https://github.com/neuropoly/axondeepseg/files/65643 …

Add simulated image when `axon_shape` is circle

---

.github/workflows/run_tests.yaml
environment.yml
setup.py
test/testing/test_statistics_generation.py

As we're moving to IVADOMED, I think we can scrap the following requirements: Tensorflow, Keras, and Albumentations. This should also conveniently make AxonDeepSeg compatible with Macs using the ARM M1 processor, as long as there's no issues on the IVADOMED side (?).
I've also updated the requirements for Mac M1 ARM compatibility (MiniForge isn't compatible with Python 3.7). I've increased it to Python 3.9, but am not sure if this will break FSLeyes compatibility. If it does, maybe we should continue anyways (or downgrade to 3.8) and see if we can resolve it on the FSLeyes side.
#523

Update reqs for Mac M1 ARM. Remove dependencies: TF, Keras, and Albumentation. Remove FSLeyes (temporarily)

---

AxonDeepSeg/download_tests.py
AxonDeepSeg/morphometrics/compute_morphometrics.py
AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
test/morphometrics/test_compute_morphometrics.py

This PR aims to handle the ZeroDivisionError that sometimes happen when computing morphometrics with the ellipse axon shape. The adopted solution is to output a NaN value in the output CSV file when that happens. What is left to do:
Resolves #557

Fix morphometrics error with ellipse axon shape

---

ads_plugin.py

Quick fix for the issue mentionned in #587 where NaNs wouldn't appear in the morphometrics file if it was generated in the GUI.

Fix NaNs not appearing when generating morphometrics with the GUI

---

ads_plugin.py

As mentionned [here](https://github.com/axondeepseg/axondeepseg/issues/334#issuecomment-1059519811), some resolution variables are no longer used since the Ivadomed integration. We just forgot to remove them when releasing the v4.

Remove some unused variables in the plugin

---

environment.yml

This PR updates the ivadomed dpendency to the newly released version 2.9.4.
The main new features relevant to ADS in the 2.9.4 version are:
- While segmenting, ONNX or PT model are chosen based on device availability (CPU/GPU), ref: https://github.com/ivadomed/ivadomed/pull/1086. The `gpu_id` is `0` by default in `segment_volume`. We could changed that in the future [here](https://github.com/axondeepseg/axondeepseg/blob/6d745492cc091576922b579bc67c56a72905b838/AxonDeepSeg/apply_model.py#L48).
- The `pixel_size_units` options [here](https://github.com/axondeepseg/axondeepseg/blob/6d745492cc091576922b579bc67c56a72905b838/AxonDeepSeg/apply_model.py#L45) now accept `mm` and `nm` in addition of `um`, ref: https://github.com/ivadomed/ivadomed/pull/1025 This will allow us to move forward with …

Update ivadomed to 2.9.4

---

environment.yml

This PR updates the ivadomed dependency to the newly released version 2.9.5.
This new version fix the loading of 16bit grayscale TIF files (related to #617).
I'm not closing the issue yet since we still need to add tests on ADS side for this.

Update ivadomed to 2.9.5

---

AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
test/morphometrics/test_launch_morphometrics_computation.py

Tying up some loose ends here. This PR addresses a bug when using the `axondeepseg_morphometrics` command with the `-i` arg pointing to a *folder*. In these cases, the xlsx/csv file was correctly written but the index + axonmyelin_index images could not be saved. Note that when launching the script from the actual directory and using `-i .`, this behavior does not manifest.
Also, the related exception was poorly handled and actually ignored. Not sure if this is the desired behavior (maybe when doing morphometrics for multiple files it's useful to ignore the exception and go on to the next folder?) I changed it but now the catch block is useless.
Resolves #553

Fix morphometrics bug when writing index/axonmyelin_index files

---

AxonDeepSeg/download_tests.py
AxonDeepSeg/morphometrics/compute_morphometrics.py
AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
AxonDeepSeg/params.py
ads_plugin.py
notebooks/02-morphometrics_extraction.ipynb
test/morphometrics/test_compute_morphometrics.py
test/morphometrics/test_launch_morphometrics_computation.py

The goal of this PR is to simplify the code around the data structures used for manipulating the results of the morphometrics computation.
As stated in #540, the current way we use data structures to store the morphometrics results can be confusing are requires to restructure a numpy array whenever we want to save the morphometrics. The current saving process actually consists of converting the restructured numpy array into a pandas.DataFrame in order to save it. So why not use a right pandasDataFrame from the start?
This modifies a good portion of the tests since the many of them use the numpy array of dictionnaries.
Bonus: This also provides a method to read csv and excel files (we previously could only read saved numpy arrays).
Resolves #540

Refactor the data structure used for storing morphometrics

---

AxonDeepSeg/ads_utils.py
AxonDeepSeg/morphometrics/compute_morphometrics.py
AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
AxonDeepSeg/segment.py
AxonDeepSeg/zoom_factor_sweep.py
docs/source/documentation.rst
test/morphometrics/test_launch_morphometrics_computation.py
test/test_segment.py

The goal of this PR is to add some form of logging for batch processing, more specifically:
I tried using python's native `logging` module but it's somewhat complex to use and, for some reason, suppresses ivadomed's output. `loguru`, on the other hand, is much simpler, the output is much nicer and everything works out of the box with almost 0 boilerplate. Here is a screenshot of what it looks like. As you can see, it looks very similar to ivadomed's output.
As of now, the behavior is to create a *axondeepseg.log* file in the working directory or open it if it already exists, then append the recorded message (info/warning/error).
Resolves #627

Add logging for segmentation/morphometrics

---

AxonDeepSeg/download_tests.py
AxonDeepSeg/morphometrics/compute_morphometrics.py
docs/source/documentation.rst
test/morphometrics/test_compute_morphometrics.py

This PR adds a flag in the morphometrics to tell the user if the axonmyelin object touches a border for faster manual filtering. Thanks to the morph. data structure refactoring, this was very quick to implement.
I tested the PR on the following test image:
According to the new `border_touching` column, the elements touching the border are the following:
```
0 1 2 3 4 7 9 12 13
```
As we can see, most of these are unusable except for id=3 where the element touches the border but is still good, so it would still require the user to take a look at the result.
Resolves #638

Add border_touching flag to morphometrics

---

AxonDeepSeg/apply_model.py
AxonDeepSeg/segment.py
AxonDeepSeg/zoom_factor_sweep.py
docs/source/documentation.rst
test/test_segment.py

This PR adds the option to segment without patches with the `--no-patch` flag in the CLI (as implemented in ivadomed v2.9.7).
The PR is still a draft, TODO:
Fixes #676

Segment images without patches

---

AxonDeepSeg/apply_model.py
ads_plugin.py
docs/source/documentation.rst

This PR is part of the RAM limitations vs. no-patch segmentation discussion in issue #703.
As discussed in meeting, it adds warnings to the user regarding the "no-patch" option:
* warn the user when using "no-patch" that this may not be suitable for larger images
* warn the user when not using "no-patch" that "no-patch" could potentially produce better results
It also includes an update of documentation and tooltip in fsleyes.
Related to #703

Add warnings related to "no-patch" option

---

test/test_segment.py

Because the Windows and Linux machines that GitHub action uses only have 7GB of ram, occasionally the CI will fail the no-patch tests that were recently added when the memory runs out (it uses approx 6GB). This PR reduces the image sizes via the pixel size for these tests, so that they (hopefully) won't fail anymore during the nightly scheduled CI runs. In addition, this will hopefully prevent some users (not happened yet) from getting fails from running the test suite after installation, also due to insufficient RAM.
Resolves #706

Change pixel size to reduce RAM usage during no-patch test

---

AxonDeepSeg/ads_utils.py
AxonDeepSeg/apply_model.py
AxonDeepSeg/integrity_test.py
AxonDeepSeg/segment.py
AxonDeepSeg/zoom_factor_sweep.py
ads_plugin.py
docs/source/documentation.rst

This PR adds an argument in the CLI and setting in FSLeyes to choose which GPU to use while segmenting.
This feature was already implemented in ivadomed in the `segment_volume` API and is useful when processing large images on our shared GPU clusters.
The default GPU ID `0` is the same as the default in ivadomed.
@Stoyan-I-A, I tried the implementation in the plugin based on the similar implementation of the overlap_value setting. It seems to work fine, let me know if that is ok. We may also need to update the ads_plugin file and/or version after the merge of #700.
Related to #703.

Add GPU ID setting in CLI and FSLeyes

---

environment.yml

The aim of this PR is to remove the version requirement of matplotlib on our side so that we use the latest FSLeyes version.
Resolves #727

[patch] remove matplotlib version requirement

---

environment.yml

Quickfix to temporarily resolve #738 by fixing the imagioio version below the latest version (2.28.0)

Fix imagio below latest version

---

plugins/napari_ADS/_widget.py

In this discussion: https://github.com/axondeepseg/axondeepseg/discussions/748 , the user encountered a bug when he tried to apply an ADS model on an image that was too small. We would expect to see a pop up message warning the user that the model was not applied but instead an AttributeError was thrown. This PR fixes this issue and the pop up message should correctly be displayed in a case like this.
Resolves #749

Fix a bug where the error message would not show up if the model couldn't be applied

---

environment.yml

Recently failed build: https://github.com/axondeepseg/axondeepseg/actions/runs/6292225299/job/17081415695#step:8:1282
Error message: 
>FAILED test/test_integrity_test.py::TestCore::test_integrity_test_script_runs_successfully - ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
Issue opened by other people that dependency's repo: https://github.com/microsoft/onnxruntime/issues/17631
#757

Patch onnxissue 1.16.0 issue

---

AxonDeepSeg/download_tests.py
AxonDeepSeg/params.py

The use of unicode to make a superscript in the morphometrics units (eg um^2) is problematic, as different interfaces won't display the same way,
eg Excel
eg TextEdit
and, while it displays correctly in pandas dataframes,
getting access to the column it's not as simple as copy-pasting the name when using unicode,
the user instead needs to go look into our code to find what the unicode was (which we don't instruct them to do),
I think simply using `um^2` should be understandable by most, and simplifies the use/visualization of the unit name across softwares.

Remove unicode in units names

---

.github/workflows/run_tests.yaml

We've recently started getting this failure on the macos CI:
```shell
Error: No installed conda 'base' environment found at !If you are using this action in a self-hosted runner that already provides its own Miniconda installation, please specify its location with a `CONDA` environment variable. If you want us to download and install Miniconda or Miniforge for you, add `miniconda-version: "latest"` or `miniforge-version: "latest"`, respectively, to the parameters for this action.
```
https://github.com/axondeepseg/axondeepseg/actions/runs/8918691441/job/24493688432

Github Actions failure: macos " No installed conda 'base' environment found at !"

---

docs/environment.yml

RTD fails on all PRs at the moment. It complains that sphinx should be at least v5.0.0

Update sphinx to fix doc build

---

docs/source/documentation.rst
install_ads
install_ads.bat
setup.py
test/test_download_models.py
test/test_download_tests.py

The documentation currently says to the users to call `download_model`, however our actual CLI command is `download_models`. As a simple fix, we can simply update the doc; however, it is a bit inconsistent that in actuality, our python **module** name is `download_model` (and makes more sense, since we can only download one model at a time I believe). So maybe changing the CLI command would be a better solution considering we're releasing 5.0 soon (this would require more changes though in the tests, installation, and CI files). Open to opinions/discussion
#829

Change "download_models" to "download_model"

---

requirements.txt

nnUnetV2 depends on acvl_utils, but didn't pin a version for it. Two days ago acvl_utils == 0.2.1 was released, but that one imports a package that is never installed (blosc2) which has lead to failing overnight tests, https://github.com/axondeepseg/axondeepseg/actions/runs/11753375787
I propose to pin the version to <0.2.1, because if acvl_utils didn't catch this missing dependency with tests or a CI, then maybe it's better to trust that they didn't miss something else in this most recent push and download an earlier version.

Pin acvl_utils!=0.2.1

---

requirements.txt

Four days ago, our nightly GithubAction CI tests started failing,
https://github.com/axondeepseg/axondeepseg/actions/runs/12366489905
A single test is failing, one that ensures consistency of the calculated morphometrics values from a test image vs one that was saved when the test was written (or updated),
```
=========================== short test summary info ============================
FAILED test/morphometrics/test_compute_morphometrics.py::TestCore::test_morphometrics_consistency - assert False
+  where False = <function allclose at 0x7fb8f4055b30>(array([0.5720214 , 0.74337605, 0.31622777, 0.69370799, 0.81355151,\n       0.49859711, 0.52833806, 0.66483182, 0.68028435, 0.79613784,\n       0.81899995, 0.5204165 , 0.38240889, 0.49708452, 0.38506605,\n       0.61509379, 0.55229652, …
```

Pin skimage<0.25

---

README.md

Currently, our logo appeared terrible for users with the dark mode setting,
eg
With this PR, the logo will alternate between two PNGs (with transparent backgrounds) for light/dark mode, the only difference between the two being the text color (black/white).
I also replaced the U-net figure with a new napari GUI GIF we introduced in our RTD in a recent PR (#850)
Resolves #480

README: Add dark/light mode compatibility

---

AxonDeepSeg/ads_utils.py
test/test_ads_utils.py
test/test_download_tests.py

This PR exists to solve a problem that isn't here yet, i.e. I only discovered it after trying the pypi route. Basically, currently the installation procedure is guaranteed to always download the models otherwise the installation fails, due to some embedded checks (running the unit tests) and explicit downloading of the data.
When we later switch to offer a pipy install, this won't be the case. And, due to the switch from setup.py to pyproject.toml, there's not really a way to do it either (and it's mainly discouraged to try and get around it); usually they recommend to tell the user to run some kind of axondeepseg init to do all that data-related stuff.
Resolves #878

Make get_existing_models_list returns None when no models exist

---

AxonDeepSeg/ads_napari/_widget.py
test/ads_napari/test_widget.py

This is a quick fix for the bug encountered by the UBC group with the latest version of ADS. The fix I suggest is pretty minimal - I don't know where else this grayscale conversion could be a problem in the plugin.
Fixes #894

Fix bug loading predictions of grayscale converted img

---

install_ads

I encountered an issue where our alias `ads_activate` would not work on a new user account on my laptop; after discussing with @joshuacwnewton we found that the culprit is that our current file in the /bin opens in a subprocess, thus not activating it in certain cases. Creating a true alias in the users zsh (or wtv) file resolves this

Create true alias for ads_activate

---

AxonDeepSeg/download_tests.py
AxonDeepSeg/morphometrics/compute_morphometrics.py
test/morphometrics/test_compute_morphometrics.py

This is mostly critical for unmyelinated axons, as the only object separation (from semantic seg to instance seg) is done with `skimage.measure.label` (whereas myelinated axons undergo a subsequent watershed segmentation step). I implemented a test that should fail with the current implementation (where we use 2-connectivity). See issue below for more details.
The image I added to the data-testing repo is the following:
Using 2-connectivity, objects 1 and 2 will be identified as a single instance. 1-connectivity fixes this.
Resolves #909

Use skimage.measure.label with 1-connectivity 
