axondeepseg/axondeepseg

AxonDeepSeg/segment.py

Fixes #59 
We do not alter original inputs anymore, we do everything with a tmp file, and delete it when done.

Work with tmp files for segmentation pipeline

---

AxonDeepSeg/segment.py

Added compatibility with tiff input format

---

README.md

Update paper ref in readme

---

.travis.yml
AxonDeepSeg/integrity_test.py

Fixes issue #60 
This is the basic setup of Travis, it will be updated when a more complete testing module will be added (see issue #76 that was added for that).

Added Travis CI to the repo

---

AxonDeepSeg/testing/segmentation_scoring.py

#88 [BUG] Fix false negative calculation for the Jaccard index

---

README.md
docs/source/documentation.rst

Add Changelog to the doc in ReadTheDocs

---

postBuild

Ref issue #94 
This branch was tested on Binder in the following link: https://mybinder.org/v2/gh/neuropoly/axondeepseg/dev_issue94?filepath=notebooks%2Fgetting_started.ipynb

Resolve issue with Binder

---

AxonDeepSeg/train_network.py

I removed the argument in the global_variables_initializer function in train_network.py, ligne 328.

Argument bug in the global_variables_initializer function in train_network.py

---

AxonDeepSeg/segment.py
README.md

Resolves #119 
I also updated the Coveralls.io badge so that it points to master now that a first build for it was made.

 [BUG] Fixes case-sensitive file extention CLI bug

---

AxonDeepSeg/__init__.py
CHANGELOG.md

I thought I had committed these two files in my previous commit in the PR, but somehow they weren't added to the commit :/ This is the second time this happens to me in 24h, in two different repos, I'll have to watch myself.

[DOC] Change version from dev to stable, update dates

---

AxonDeepSeg/apply_model.py

While performing segmentation though ADS performs segmentation it throws the following session closed exception. This quick PR aims to resolve this issue.

Remove session close exception

---

AxonDeepSeg/postprocessing.py
ads_plugin.py

Related Issues : #270 , #268
Changes:
- Added the postprocessing library
- The load mask button now uses an axon+myelin image

FSLeyes plugin: Load mask takes a single myelin/axon file and small refactoring

---

CHANGELOG.md

Fixes #287 
This PR fixes the formatting of changes in version 3 section of changelog.md.

Fix format in Changelog

---

AxonDeepSeg/ads_utils.py
ads_plugin.py

[FSLeyes plugin] changed Image.save/open with ads_utils.read/write

---

AxonDeepSeg/ads_utils.py
AxonDeepSeg/data_management/dataset_building.py
docs/source/documentation.rst
test/test_ads_utils.py
test/test_segment.py

[Bug] Resolve segment folder bug when using relative paths

---

AxonDeepSeg/train_network.py
requirements.txt
test/test_train_network.py

Resolves #380 
Solution from https://github.com/neuropoly/spinalcordtoolbox/pull/2988

Pin h5py~=2.10.0 as a workaround for upstream Keras/TensorFlow issues

---

docs/source/documentation.rst

Fix notebook links in doc

---

CONTRIBUTING.rst
README.md
docs/source/documentation.rst
docs/source/index.rst
docs/source/license_contributors.rst

The first two commits are trivial changes.
The third commit could spark World War Vi.

Documentation updates

---

.gitignore

In the recent merged PR (#457), I forgot to include Simeon's model in[ `.gitignore`](https://github.com/neuropoly/axondeepseg/blob/master/.gitignore) file. This PR does a quick-fix to that. This will prevent devs from committing the model binaries by mistake.

Add Simeon's model to .gitignore

---

docs/source/documentation.rst

This quick PR aims to fix the docs for the newly integrated model (`model_seg_pns_bf`) in ADS. 
RTD for this PR is rendered [here](https://axondeepseg--485.org.readthedocs.build/en/485/).

Fix docs for optical microscopy model

---

AxonDeepSeg/download_model.py

With this modification, models are now downloaded from Github instead of OSF.
I had to play around with the github API in order to get it to work properly. IMHO, it isn't very well documented and I had to find a way to communicate with the API without installing a new dependency. The `requests` module does the trick for us.
I think the way it worked with OSF was simpler, as now we have to fetch the release tag and insert it in the download URL, but at least it works and we will always get the latest version.
You can do the following:
```bash
$ cd axondeepseg
$ py.test test/test_download_models.py
```
(or run all tests)
Related to migration of repositories from OSF to Github #506 
BTW first PR here, feel free to tell me if something isn't right

Download models from Github repo

---

AxonDeepSeg/download_tests.py

Similar to ADS models which were hosted on OSF, this PR takes care of the test files(`__test_files__`) which were hosted on OSF (https://osf.io/vqt94/?action=download) earlier and now being hosted on GitHub (https://github.com/axondeepseg/data-testing). This PR aims to download these test files hosted on GH to ADS.
No additional tests are required. The previous unit test [test_download_test.py](https://github.com/neuropoly/axondeepseg/blob/master/test/test_download_tests.py) was sufficient for this change.

Link the `test_files` to GitHub

---

AxonDeepSeg/download_tests.py

This PR aims to update the link of the test files to the latest release. For more details, refer [here](https://github.com/neuropoly/axondeepseg/pull/534#issuecomment-868644053)

Small fix for  `__test_files__` link

---

docs/source/documentation.rst

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blame/081078d85c852afede913064ef7f4d9e45623f46/documentation/source/user_section/fsleyes.rst#L37-L39

Update embedded video syntax to SCT's

---

docs/source/documentation.rst

Requested on: https://neuropoly.slack.com/archives/CB0KLDR09/p1635106787007200
We will also have to remove the old videos from youtube:
https://youtu.be/qzWeG5vaVyo
https://youtu.be/dz2LqQ5LpIo

Update links videos

---

AxonDeepSeg/download_tests.py
test/morphometrics/test_compute_morphometrics.py

This PR adds a unit test that compares morphometrics values computed from `__test_files__/__test_demo_files__/image.png` with a reference axonlist.npy file added in the testing data.
Discussed in #589

Add test for morphometrics consistency

---

AxonDeepSeg/morphometrics/compute_morphometrics.py

Update for regionprops calls for retrocompatibility

---

docs/source/conf.py
docs/source/documentation.rst

This simply adds the model repository links in the doc.
Following the models README update from #599

Add model repo links in the doc

---

test/test_segment.py

Add test for 16bit TIF grayscale file, which was in the test files already, I just never wrote a test for it. Linked to issue #617, which has already been resolved on the IVADOMED side by @mariehbourget in a recent release.
#617

Add test for 16bit TIF grayscale file

---

environment.yml

Bug report on the dependency's page: https://github.com/protocolbuffers/protobuf/issues/10051

Fix ONNX dependency to version prior to bug introduction

---

environment.yml

2 days ago nibabel released a new major version. Ivadomed pinned nibabel to 3.2 but ivadomed is the last line in our environment.yml file, so conda collects the latest version first and then has to uninstall it (which causes a permission error on windows).
Resolves #654

Pin nibabel

---

environment.yml

Update IVADOMED to the latest release, which should suppress some warnings.
#666

Update IVADOMED version

---

.gitignore
AxonDeepSeg/ads_utils.py
environment.yml
test/visualization/test_get_masks.py

Merge old (forgotton about) branch to newly created one

Ignore logs, update scikit, change deprecated imread

---

.gitignore
AxonDeepSeg/ads_utils.py
AxonDeepSeg/postprocessing.py
environment.yml
test/morphometrics/test_compute_morphometrics.py
test/morphometrics/test_launch_morphometrics_computation.py
test/test_ads_utils.py
test/test_download_models.py
test/test_download_tests.py
test/test_integrity_test.py
test/test_params.py
test/test_postprocessing.py
test/test_segment.py
test/testing/test_launch_performance_metrics.py
test/testing/test_noise_simulation.py
test/testing/test_segmentation_scoring.py
test/visualization/test_colorization.py
test/visualization/test_generate_axons_from_myelin.py
test/visualization/test_get_masks.py
test/visualization/test_merge_masks.py
test/visualization/test_simulate_axons.py

This suppresses all the warnings that are due to our code. There are still ~20 warnings remaining, all due to fixed dependencies or their dependencies, which are out of our control until we decide on bring them up-to-date.
#666

Resolves warnings

---

ads_plugin.py

Adds the "no-patch" option to the settings in the FSLeyes plugin. This option was added to the CLI in #696.
Resolves #699

Add no patch option to the FSLeyes plugin settings menu

---

environment.yml

Update ivadomed version to latest release 2.9.8 in environment.yml

Update ivadomed version to 2.9.8

---

AxonDeepSeg/ads_utils.py

Fixes bug where images with higher than 8 bits were cutoff, instead of converted properly to 8 bit while retaining their range.
#709

Fix 16 bit conversion bug

---

environment.yml

- [ N/A ] I've added relevant tests for my contribution
- [ N/A ] I've updated the documentation and/or added correct docstrings
It seems we no longer use openCV in our code and it has caused a problem in #711 so we might as well remove it.
Resolves #712

remove openCV requirement

---

.github/pull_request_template.md

Fixes a broken link in the PR template
Resolves #719

Fix broken link

---

.readthedocs.yml
docs/source/_static/css/custom.css
docs/source/conf.py
docs/source/documentation.rst

Added a Testimonials section in our RTD, formatted it similarly to SCT's page, and added our first three testimonials.
Preview here: https://axondeepseg.readthedocs.io/en/ads-testimonials/documentation.html#testimonials
#759

Add testimonial section in documentation

---

docs/source/documentation.rst

Just a small change in the documentation to add one testimonial, so I'll force merge to main after the build passes and have looked at the RTD page to make sure it formatted correctly.

Add A. Wheeler testimonial

---

docs/environment.yml
docs/source/documentation.rst

This PR adds some details about the morphometrics computation. In particular, the diameter and eccentricity estimations are detailed. I would also like to eventually describe how the perimeter is computed, but #776 needs to be adressed first.

Add morphometrics algorithms description

---

.github/workflows/run_tests.yaml

Coveralls reporting was broken, this PR fixes it by switching to only using the Coveralls Github Actions way (instead of a combination of that + the coveralls pipy)
Resolves #818

Consolidate coveralls services

---

docs/source/documentation.rst

Fixes a Sphinx syntax bug where the youtube video wouldn't show up if there's not a space on the line before `.. raw:: html`
Here's a link to the fixed build: https://axondeepseg.readthedocs.io/en/mb-youtube/documentation.html#graphical-user-interface-gui
Resolve #823

Fix youtube bug in docs

---

plugins/napari_ADS/napari.yaml

in #800, we forgot to push a suggestion by @joshuacwnewton . This was raised by a user in #826 
Resolves #827, linked to discussion #826

fix napari plugin not launching properly on Windows

---

.github/workflows/run_tests.yaml
AxonDeepSeg/download_model.py
install_ads
install_ads.bat
setup.py
test/test_download_models.py

The option of customizing the directory where models were downloaded wasn't functioning for the CLI - this PR fixes that and reintroduces that feature.
Resolves #835

Fix download_models bug - download to path

---

AxonDeepSeg/apply_model.py
test/test_apply_model.py

Class value check - Change error to warning

---

AxonDeepSeg/integrity_test.py
docs/source/documentation.rst
setup.py

I'm not adding a new test for this, because it would cause an infinite loop 😃
Resolves #822

Add CLI option to run all tests

---

.readthedocs.yml
docs/environment.yml
docs/source/conf.py
docs/source/documentation.rst
docs/source/index.rst
docs/source/requirements.txt

This PR adds the option `fail_on_warning` to `.readthedocs.yml`, which will cause the RTD documentation build to fail if there are any Sphinx warnings.
Then, to ensure the docs pass, this PR adds changes to the docs until there are no more warnings.
Fixes #579.

Set `fail_on_warning = True` and resolve documentation warnings to ensure docs pass

---

docs/source/index.rst

I replace the u-net figure on the landing page with an animation of the napari GUI / ADS plugin
View preview: https://axondeepseg.readthedocs.io/en/mb-791/
Resolves #791

Add Napari Plugin animation in doc

---

AxonDeepSeg/segment.py

Sample output
```
===================================================================================
2024-12-19 22:10:12.199 | INFO     | AxonDeepSeg.segment:main:263 - AxonDeepSeg v5.0.0 (master: 4a5fc6c9898437c98287d1797c8d0d084fac1b00)
2024-12-19 22:10:12.200 | INFO     | AxonDeepSeg.segment:main:266 - Command line arguments: {'imgpath': ['test/__test_files__/__test_demo_files__/image.png'], 'model': None, 'verbose': 0, 'gpu_id': -1}
2024-12-19 22:10:12.218 | INFO     | AxonDeepSeg.apply_model:axon_segmentation:147 - Running inference on device: cpu
2024-12-19 22:10:14.761 | INFO     | AxonDeepSeg.apply_model:axon_segmentation:157 - Model successfully loaded.
```
Resolves #671

Log CLI args, add breakline

---

docs/source/documentation.rst

Resolves #857 , see preview: https://axondeepseg.readthedocs.io/en/mb-857/documentation.html#graphical-user-interface-gui
Resloves #857

Fix crosslink bug in documentation

---

AxonDeepSeg/ads_utils.py
AxonDeepSeg/download_tests.py
test/test_ads_utils.py
test/test_download_tests.py

Update imread/imwrite functionality and tests

---

README.md

Added link to the generalist model preprint in readme

Add generalist preprint in readme

---

docs/source/documentation.rst

The image "77.png" wasn't automatically downloaded during install, so I changed the test image in the RTD documentation to use the ones from our tests. 
Resolves #644

Change test image(s) in rtd

---

AxonDeepSeg/download_tests.py
requirements.txt

New morphometrics reference table was saved and uploaded to the data-testing repo, and scikitlearn was unpinned here
Resolves #849

Remove scikitlearn pinned version and use updated reference pickle for morphometrics data testing

---

plugins/napari_ADS/_widget.py

In #844, we refactored config.py to AxonDeepSeg/params.py. We missed changing one of the imports in the napari widget, so it's trying to import a file that doesn't exist. I just imported params as config in my fix because it's the quickest way to fix and it's an urgent fix

Fix missing config import in napari

---

AxonDeepSeg/ads_utils.py
AxonDeepSeg/morphometrics/compute_morphometrics.py
AxonDeepSeg/morphometrics/launch_morphometrics_computation.py
docs/source/documentation.rst

I also removed two debugging print statements from a previous PR that were accidentally left there.
Resolves #863

Set border morphometrics true by default

---

AxonDeepSeg/download_tests.py
pyproject.toml

All our tests started failing again due to the data consistency check for our morphometrics,
https://github.com/axondeepseg/axondeepseg/actions/runs/13405546289/job/37444702835
This is due to some changes made in scikit-learn in the version they pushed yesterday (0.25.2) that seems to have tried to revert the issue we first flagged in #849, however when I checked the old pkl files the values dont appear to have reverted to their original value (see https://github.com/scikit-image/scikit-image/pull/7702#issuecomment-2668787118). So this PR pushes an update to our data-testing repo version that now includes a new pkl file that I generated, and updates our requirement for sckit-image to be >=0.25.2
#849 and https://github.com/scikit-image/scikit-image/pull/7702

Update skimage and data-testing versions, update morphometrics pkl for consistency check

---

AxonDeepSeg/ads_utils.py
AxonDeepSeg/download_tests.py
AxonDeepSeg/morphometrics/aggregate.py
AxonDeepSeg/morphometrics/compute_morphometrics.py
AxonDeepSeg/params.py
docs/source/documentation.rst
install_ads
pyproject.toml
test/morphometrics/test_aggregate.py
test/test_ads_utils.py
test/test_download_models.py
test/test_download_tests.py

Morphometric aggregation + visualization

---

.github/workflows/pipy_install_tests.yaml

Dummy PR: verify PR branch name rule 

---

.github/workflows/pipy_install_tests.yaml
CHANGELOG.md

This PR makes a change where the pipy_install_tests.yaml won't run on all PRs now (since they require an updated pip build); it will only run for new release branches `release/x.x.x`

Change pipy actions rule: only build on release PRs

---

.github/workflows/pipy_install_tests.yaml

Ensure pip tests only run tests in the latest release branch
